/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/armfram2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-0.173, 162.946, -0.348]} rotation={[0, 0, -1.572]}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone006} />
        </group>
        <group name="Armature001" position={[-0.173, 162.946, -41.785]} rotation={[0, 0, -1.572]}>
          <primitive object={nodes.Bone_1} />
          <primitive object={nodes.Bone006_1} />
        </group>
        <group name="Cylinder" position={[-7.059, 184.971, -20.55]} scale={[5.564, 6.028, 5.334]}>
          <mesh name="Cylinder002" castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={materials['Pelv.001']} />
          <mesh name="Cylinder002_1" castShadow receiveShadow geometry={nodes.Cylinder002_1.geometry} material={materials['Pelv.003']} />
          <mesh name="Cylinder002_2" castShadow receiveShadow geometry={nodes.Cylinder002_2.geometry} material={materials.Bolt} />
          <mesh name="Cylinder002_3" castShadow receiveShadow geometry={nodes.Cylinder002_3.geometry} material={materials.connectors} />
          <mesh name="Cylinder002_4" castShadow receiveShadow geometry={nodes.Cylinder002_4.geometry} material={materials['connectors.002']} />
          <mesh name="Cylinder002_5" castShadow receiveShadow geometry={nodes.Cylinder002_5.geometry} material={materials['Bolt.002']} />
          <group name="Empty" position={[0.243, -1.615, -0.181]} scale={[2.293, 2.165, 6.662]} />
        </group>
        <group name="walk_Path001" position={[-23.353, -0.381, -42.178]} rotation={[Math.PI / 2, 0, 0]} scale={[0.672, 1, 0.772]} />
        <group name="walk_Path" position={[-26.403, -0.381, -0.311]} rotation={[Math.PI / 2, 0, 0]} scale={[0.672, 1, 0.772]} />
      </group>
    </group>
  )
}

useGLTF.preload('/armfram2.glb')
